export const GET_SALES_PERFORMANCE = "GET_SALES_PERFORMANCE";
export const GET_INVENTORY_MGT = "GET_INVENTORY_MGT";
export const SET_TOTAL_SELL_IN = "SET_TOTAL_SELL_IN";
export const SET_TOTAL_SELL_OUT = "SET_TOTAL_SELL_OUT";
export const SET_DATE_FILTER = "SET_DATE_FILTER";
export const SET_DASHBOARD_TAB = "SET_DASHBOARD_TAB";
