export const ADD_DISTRIBUTOR = "ADD_DISTRIBUTOR";
export const DELETE_DISTRIBUTOR = "DELETE_DISTRIBUTOR";
export const EDIT_DISTRIBUTOR = "EDIT_DISTRIBUTOR";
export const VIEW_ALL_DISTRIBUTOR = "VIEW_ALL_DISTRIBUTOR";
export const VIEW_SINGLE_DISTRIBUTOR = "VIEW_SINGLE_DISTRIBUTOR";
export const VIEW_SINGLE_KPO = "VIEW_SINGLE_KPO";
export const VIEW_MY_DISTRIBUTORS = "VIEW_MY_DISTRIBUTORS";
