const colors = require("tailwindcss/colors");

module.exports = {
  purge: ["./src/**/*.{js,jsx,tx,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      macbook16: "3072px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: colors.black,
      white: colors.white,
      gray: colors.coolGray,
      red: colors.red,
      yellow: colors.amber,
      green: colors.emerald,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.violet,
      pink: colors.pink,
      basic: "#B12025",
      active: "#2D2F39",
      default: "#74767E",
      "default-b": "#DFE0E4",
      "grey-40": "#9799A0",
      "grey-70": "#50525B",
      "grey-85": "#2D2F39",
      "grey-100": "#090B17",
      "grey-text": "#4D4D4D",
      "red-main": "#B11F24",
      "red-error": "#FF0000",
      critical: "#D82C0D",
      "critical-bg": "#FFF4F4",
    },
    backgroundColor: (theme) => ({
      ...theme("colors"),
      "red-main": "#B11F24",
    }),
    backgroundImage: {
      none: "none",
      "gradient-to-t": "linear-gradient(to top, var(--tw-gradient-stops))",
      "gradient-to-tr":
        "linear-gradient(to top right, var(--tw-gradient-stops))",
      "gradient-to-r": "linear-gradient(to right, var(--tw-gradient-stops))",
      "gradient-to-br":
        "linear-gradient(to bottom right, var(--tw-gradient-stops))",
      "gradient-to-b": "linear-gradient(to bottom, var(--tw-gradient-stops))",
      "gradient-to-bl":
        "linear-gradient(to bottom left, var(--tw-gradient-stops))",
      "gradient-to-l": "linear-gradient(to left, var(--tw-gradient-stops))",
      "gradient-to-tl":
        "linear-gradient(to top left, var(--tw-gradient-stops))",
    },
    backgroundOpacity: (theme) => theme("opacity"),
    // borderColor: (theme) => ({
    //   ...theme('colors'),
    //   DEFAULT: theme('colors.gray.200', 'currentColor'),
    // }),
    borderColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: theme("colors.gray.300", "currentColor"),
      "grey-25": "#BBBDC2",
    }),
    cursor: {
      auto: "auto",
      default: "default",
      pointer: "pointer",
      wait: "wait",
      text: "text",
      move: "move",
      "not-allowed": "not-allowed",
    },
    fontFamily: {
      customRoboto: ["Roboto", "sans-serif"],
      customBarlow: ["Barlow", "sans-serif"],
      customGilroy: ["Gilroy", "sans-serif"],
    },
    fontSize: {
      xs: ["0.75rem", { lineHeight: "1rem" }],
      small: ["0.875rem", { lineHeight: "1rem" }],
      larger: ["0.875rem", { lineHeight: "1.5rem" }],
      "small-text": ["1rem", { lineHeight: "1.25rem" }],
      "large-text": ["1.75rem", { lineHeight: "2rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
      "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "5xl": ["3rem", { lineHeight: "1" }],
      "6xl": ["3.75rem", { lineHeight: "1" }],
      "7xl": ["4.5rem", { lineHeight: "1" }],
      "8xl": ["6rem", { lineHeight: "1" }],
      "9xl": ["8rem", { lineHeight: "1" }],
    },
    fontWeight: {
      thin: "100",
      extralight: "200",
      light: "300",
      normal: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
      extrabold: "800",
      black: "900",
    },
    gap: (theme) => theme("spacing"),

    outline: {
      none: ["2px solid transparent", "2px"],
      white: ["2px dotted white", "2px"],
      black: ["2px dotted black", "2px"],
      orange: ["2px solid #F49C00", "2px"],
    },
    padding: (theme) => theme("spacing"),
    placeholderColor: (theme) => theme("colors"),
    placeholderOpacity: (theme) => theme("opacity"),
    textColor: (theme) => theme("colors"),
    textOpacity: (theme) => theme("opacity"),
    extend: {
      width: {
        "1/7": "14.2857143%",
        "2/7": "28.5714286%",
        "3/7": "42.8571429%",
        "4/7": "57.1428571%",
        "5/7": "71.4285714%",
        "6/7": "85.7142857%",
        modal: "50rem",
        "large-modal": "60rem",
        "input-sm": "21rem",
        "input-lg": "44rem",
        "mini-modal": "40rem",
      },
      height: {
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        modal: "36rem",
        "large-modal": "45.5rem",
        "main-modal": "40rem",
        "sub-modal": "37rem",
        "mini-modal": "11.5rem",
        "small-modal": "18.5rem",
      },
    },
  },
  variants: {
    borderColor: ["DEFAULT", "focus", "hover"],
    extend: {},
  },
  plugins: [require("tailwind-scrollbar-hide")],
};
