export const TOTAL_SALES = "TOTAL_SALES";
export const TOTAL_VOLUME_SOLD = "TOTAL_VOLUME_SOLD";
export const SELECTED_DATE_RANGE = "SELECTED_DATE_RANGE"
export const SHOW_CALENDAR = "SHOW_CALENDAR"
export const ACTIVE_CUSTOMERS = "ACTIVE_CUSTOMERS";
export const INVOICE_DATA = "INVOICE_DATA"

