export const GET_COMPANY_DROPPOINT = "GET_COMPANY_DROPPOINT";
export const ADD_COMPANY_DROPPOINT = "ADD_COMPANY_DROPPOINT";
export const SET_FROM_DROPPOINT = "SET_FROM_DROPPOINT";
export const SET_TO_DROPPOINT = "SET_TO_DROPPOINT";