export const DIST_CODE = "DIST_CODE"
export const SHOW_CALENDAR = "SHOW_CALENDAR"
export const SHOW_ANALYTICS_CALENDAR = "SHOW_ANALYTICS_CALENDAR";
export const SELECTED_ANALYTICS_DATE_RANGE = "SELECTED_ANALYTICS_DATE_RANGE";
export const SELECTED_DATE_RANGE = "SELECTED_DATE_RANGE";
export const RESET_SELECTED_ANALYTICS_DATE_RANGE = "RESET_SELECTED_ANALYTICS_DATE_RANGE";